In [60]:
import numpy as np


In [173]:
# A. Stwórz losową 1-wymiarową numpy array o długości 15 elementów. 
# Następnie oblicz jej minimum, maksimum oraz odchylenie standardowe.
a_npy = np.random.randint(10, size=15)
print(a_npy)
print(a_npy.min())
print(a_npy.max())
print(a_npy.std())

[1 8 7 0 4 8 5 5 0 5 1 8 8 2 3]
0
8
2.936362072739365


In [180]:
# B. Stwórz losową tablicę 2-wymiarową numpy array 4 wiersze x 4 kolumny, 
# a następnie oblicz sumę wartości dla każdej kolumny oraz dla każdego wiersza.
b_npy = np.random.randint(10, size=(4,4))
print(b_npy)

print(b_npy.sum(axis=0))
print(b_npy.sum(axis=1))


[[5 9 0 5]
 [8 2 5 0]
 [3 0 7 8]
 [6 9 6 0]]
[22 20 18 13]
[19 15 18 21]


In [171]:
# C. Stwórz tablicę 2-wymiarową 5 wierszy x 5 wierszy, 
# w której każda wartość będzie o 3 większa od poprzedniej.
#  Podaj indeksy każdej wartości parzystej większej od 10.
list = np.arange(0,75,3)
list2 = np.reshape(list, (-1, 5))
print(np.argwhere(list2 > 10 & (list2 % 2 ==0)))



[[0 1]
 [0 2]
 [0 3]
 [0 4]
 [1 0]
 [1 1]
 [1 2]
 [1 3]
 [1 4]
 [2 0]
 [2 1]
 [2 2]
 [2 3]
 [2 4]
 [3 0]
 [3 1]
 [3 2]
 [3 3]
 [3 4]
 [4 0]
 [4 1]
 [4 2]
 [4 3]
 [4 4]]
