In [5]:
import numpy as np


In [ ]:
# A. Stwórz losową 1-wymiarową numpy array o długości 15 elementów. 
# Następnie oblicz jej minimum, maksimum oraz odchylenie standardowe.
a_npy = np.random.randint(10, size=15)
print(a_npy)
print(a_npy.min())
print(a_npy.max())
print(a_npy.std())

[4 8 7 9 3 0 3 8 0 3 7 8 0 7 7]
0
9
3.129785225148134


In [6]:
# B. Stwórz losową tablicę 2-wymiarową numpy array 4 wiersze x 4 kolumny, 
# a następnie oblicz sumę wartości dla każdej kolumny oraz dla każdego wiersza.
b_npy = np.random.randint(10, size=(4,4))
print(b_npy)

print(b_npy.sum(axis=0))
print(b_npy.sum(axis=1))


[[6 6 8 2]
 [2 7 5 5]
 [3 4 8 5]
 [7 2 7 1]]
[18 19 28 13]
[22 19 20 17]


In [8]:
# C. Stwórz tablicę 2-wymiarową 5 wierszy x 5 wierszy, 
# w której każda wartość będzie o 3 większa od poprzedniej.
#  Podaj indeksy każdej wartości parzystej większej od 10.
c_npy = np.random.randint(10, size=(5,5))
print(c_npy)



[[3 5 3 1 8]
 [3 4 3 6 5]
 [0 6 9 8 7]
 [0 3 1 0 4]
 [1 3 2 4 7]]
